name: Generate Snake

on:
  schedule:
    # Run at 12 AM and 12 PM UTC
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

# Ensure GitHub Actions has the correct permissions
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Snake
        run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} python generate_snake.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          force_orphan: true
